### ISSUE TITLE
Channel Settings: style fixes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1261]
This a mini-epic of style fixes for the channel settings. Since these only affect moderators, they are lower priority than other fixes that more users will see. 

### acceptance criteria
- [ ] #1246 Channel settings: styling of members tab 
- [ ] #1203 Moderator UI doesn't match the design
- [ ] #1127 Channel settings: CTA button and styling tweaks to image upload UI
- [ ]  #1105 Snackbar messages get squeezed at narrow widths bug (channel settings only)

### related issues
- [ ] #1218 Cancel button on channel banner / avatar dialogs brings you back to the channel page

**Comment by pdpinch** [comment]
Looks like this is all done.
