### ISSUE TITLE
Channel Search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1316]
As a user I'd like to be able search within channels. I expect to see relevant posts, comments and user profiles in my search results. 

InVision: [some results](https://invis.io/9EN908ZQPAX#/322898017_Channel_ClimateX_Search_Channel_New) and [no results](https://invis.io/9EN908ZQPAX#/322898016_Channel_ClimateX_Search_Channel_No_Results) and [mobile results](https://invis.io/9EN908ZQPAX#/326140814_Mobile_ChannelSearch)
Zeplin: [desktop](https://zpl.io/VxlD5eg) and [mobile](https://zpl.io/aN9ByMk)

Note that these designs include some changes to the channel header, which come under the epic #1327.

### acceptance criteria
- [x] index posts, comments and profiles
- [x] management command for reindexing all posts, comments and profiles
- [x] incrementally update index when posts, comments and profiles are added or edited
- [x] REST API 
- [x] default sort is relevance 
- [x] filter on all (default), posts, comments and profiles
- [x] anonymous users get the same results, for public channels
- [x] anonymous users get no results for private channels 
- [x] users who are not a member of private channel get no results when searching that channel
- [x] result page uses new channel header, implemented in #1327

### Questions
- What are sorting options? "Active" "Top" and "New" aren't relevant for profiles
  **A** for this issue, we'll only support sort by relevance

**Comment by pdpinch** [comment]
I added the design for mobile results and a some acceptance criteria to the description. Hopefully it's nothing unexpected.

**Comment by pdpinch** [comment]
Added Zeplin link for mobile design

**Comment by pdpinch** [comment]
@noisecapella @mbertrand what else needs to be done here?

**Comment by noisecapella** [comment]
The only thing left is sorting. Should we do that here or as another issue later?

**Comment by pdpinch** [comment]
The plan for now is to only do relevance sorting, since that's the only one we can do consistently across posts, comments and profiles. 

I just answered the question in the description.

**Comment by pdpinch** [comment]
We can close this now. 🎉

We will have some follow-up issues for styling, and how to deal with the various buttons on the post summary and comment cards.
