### ISSUE TITLE
Article Post form

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1326]
Designs coming soon. 

On the front-end, this should behave similar to writing articles on LinkedIn. Users can add any number of content modules, choosing from a short list, e.g. text, image, link, code, etc. In this way, they can build up a long-form post. 

After investigating several prosemirror implementations, we have decided to try to implement this with CKEditor which meets our integration requirements but has more functionality in the standard distribution (similar to django's "batteries included" approach).  

### acceptance criteria:
- [x] #1454 Custom build of ckeditor
- [x] #1455 Light integration of CKEditor
- [x] #1456 add Easy Image support

### related issues
- #1436 backend
- #1549 edit article
- #1457 add embed support

**Comment by pdpinch** [comment]
We will also need to consider how these blog/articles can be edited once saved.

**Comment by pdpinch** [comment]
- [ ]   Alice will research how to create the UI/UX with prose mirror. 
  - How to serialize multiple text boxes?  
  - How to render? Can prosemirror help?
- [ ] How to serialize to the app
- [ ] how to serialize to search?

**Comment by pdpinch** [comment]
@aliceriot please take a look at https://github.com/pubpub/pubpub-editor/tree/v5, in particular, how are they serializing the data from multiple sources, how do they render and how do they rehydrate for editing. I've heard from the developer that they're planning to release the v5 branch in November.

**Comment by pdpinch** [comment]
I updated the description to reflect our decision to try CKEditor and added checkboxes for individual issues.
