### ISSUE TITLE
Channel Header design updates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1327]
Zeplin: https://zpl.io/bWLwOyP
InVision: https://invis.io/9EN908ZQPAX#/324748827_Channel_Full_Update_10_Oct

### acceptance criteria 
- [x] Channel banner: update the height of the channel banner in the template to 200px
- [x] Channel banner: update the height to 200px in the Channel settings form
- [x] Channel banner: Standardize on **one** background color, with no gradient
- [x] Channel banner: Add a semitransparent gradient *above* the channel title, headline and banner to help make the text more legible (see Zeplin for details)
- [x] Left nav: adjust the spacing of items in the left nav, based on Zeplin. 
  - [x] close up the gap between the compose button & the "channels I moderate" header
- [x] Channel Nav: Change "Posts" tab on channel pages to "Home"
- [x] Channel Nav: add white tab area across width of page 
- [x] Channel Nav: restyle the channel tabs
- [x] Channel Nav: remove the "All" filter in the channel template (we have no plans as yet for filtering channels)
- ~~move the channel sort dropdown to the left (where the filter used to be)~~ (don't move it)
- [x] Channel Avatar: Standardize on one background, without gradient
- [x] Channel Avatar: update the font size of the initials

### related issues
- this affects the location of the channel search form
- there are similar changes to the home page, but I don't think they share components

**Comment by pdpinch** [comment]
I updated the description based on some tweaks and feedback. The designs still haven't quite caught up.

**Comment by pdpinch** [comment]
I updated the description with the new designs. They should be in sync with all the acceptance criteria.

**Comment by rhysyngsun** [comment]
@pdpinch the mockups still show a gradient on the channel banner, if you can just let me know which color to make it, I can just plug that in

**Comment by pdpinch** [comment]
It's a little hard to interpret in Zeplin, but I think the background color is `#20316d` and then there's a semitransparent overlay `linear-gradient(to bottom, rgba(0, 0, 0, 0.19), rgba(0, 0, 0, 0.5))`

**Comment by rhysyngsun** [comment]
I'll try to do determine what that computes out to as a single gradient then.

**Comment by pdpinch** [comment]
I updated the description add another criteria for the channel avatar.
