### ISSUE TITLE
Site search

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1397]
As a user I'd like to be able search across all channels. I expect to see relevant posts, comments and user profiles in my search results.

InVision: https://invis.io/9EN908ZQPAX#/326140621_Home_Search 
Zeplin: https://zpl.io/VKlAY8E

### acceptance criteria
- [x] enable search box in header
- [x] index posts, comments and profiles
- [x] management command for reindexing all posts, comments and profiles
- [x] incrementally update index when posts, comments and profiles are added or edited
- [x] REST API 
- [ ] default sort is relevance 
- [x] filter on all (default), posts, comments and profiles
- [x] anonymous users get no results from private channels
- [x] logged in users get no results from private channels for which they are not a member

### Questions
- What are sorting options? "Active" "Top" and "New" aren't relevant for profiles
- Do we search all profiles, or only profiles where the user is a member of a public channel?

**Comment by noisecapella** [comment]
Is there a mobile mockup? I'm not sure if there's room for the search icon:
![mobile_without_site_search](https://user-images.githubusercontent.com/863262/48504871-c613a900-e813-11e8-89d5-cede7f07c18c.png)

**Comment by pdpinch** [comment]
#1448 (which just merged) should address this. 

Mobile mockup at https://zpl.io/bAE6Yy8

**Comment by noisecapella** [comment]
I'm looking over the checkboxes, have we figured out what we want to do for sort yet?
