### ISSUE TITLE
allow MIT users to create new private channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1402]
As an admin, I'd like to make channel creation self-service. Limiting it to MIT users and to private channels, gives me a way to try it out slowly at first. 

As an MIT user, I'd like to be able to create a new private channel to create a space for a selected group of users. 

Zeplin: https://zpl.io/aNoye4Q
InVision: https://invis.io/9EN908ZQPAX#/324309977_Create_Channel_Step_1

### requirements
- [ ] build off of existing channel creation form
- [ ] allow anyone with a Touchstone login to access the form
- [ ] we will distribute the URL manually at first. No link in the UI
- [ ] display all the channel type options, but disable public and restricted for now
- [ ] after created the channel, direct the user to the channel settings
- [ ] #1400 allow moderators to invite new users to private channels
- [ ] #1392 when creating channel, set membership_is_managed to false
- [ ] #1369 Channels should be owned by the indexing user

**Comment by mbertrand** [comment]
Currently the channel creation form will add the logged in user as a moderator but not a subscriber, and so the channel will not appear in the sidebar.  The user should be subscribed as well.

**Comment by pdpinch** [comment]
When we work on the channel creation form, we should validate the channel name. 

Currently, if the name is too long (or has other validation issues), the API returns a 500: 

Sentry issue: [DISCUSSIONS-TY](https://sentry.io/organizations/mit-office-of-digital-learning/issues/1037906627/?referrer=github_plugin)
