### ISSUE TITLE
Epic: Article Post Type

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1410]
##### Creating an Article Post
- Frontend:
  - [ ] Editor should support these types at a minimum:
    - [x] Text
    -  [x] Image (via a file upload)  
    - [ ] Media links (Embedly)
  - [x] Content of big post will be viewable inline as a regular post
  - [x] Editing will also happen inline like regular posts
- Backend:
  - [x] Extend our current posts API:
    - [x] Don't allow creation of this post type if the channel settings don't enable it
    - [x] Add shadow column for `post_type` to support this extended "article" post type. In reddit this will be stored as an `"any"` type, but the shadow column will override this value when returning and storing data.
    - [x] Add a `article_text` field to post API backed by a `JSON` field in the django app
   - [x] Add API to support multiple image uploads per article
   - [x] Search:
     - [x] Content of post should be indexed (need to determine how to best do this in ES, ideally balancing flexibility with complexity of implementation)

##### Channel Settings
- Frontend:
  - [x] This should be configurable as an additional "post type" in the channel admin UI
- Backend: 
  - [x] Shadow and extend the supported post types to add the "article" type (#1495)

**Comment by pdpinch** [comment]
We have basic media support in the current version. Adding full embedly support will come later.
