### ISSUE TITLE
keep track of channel followers

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1420]
In discussing #1249 we learned that reddit does not have an API for getting a list of subreddit subscribers ("channel followers" in discussions). In order to be able to count and list followers, we will need to store this relationship in django. 

### acceptance criteria
- [x] model for storing user/channel subscription status
- [x] update the subscribe API in discussions to store the subscription state of the user
- [x] whenever the subscription state is updated, update the ES profile index
- [x] update the `backpopulate_default_channel` management command to also store subscriptions
- [x] api for getting a list of followers of a channel 

### related issues
- button and api for following/unfollowing channels

**Comment by mbertrand** [comment]
@pdpinch does it make sense to add 'Update the Elasticsearch profile doc (`author_channel_membership`) when channel subscription status changes' to this issue, or create a new issue for it?

**Comment by mbertrand** [comment]
@pdpinch is it correct that a channel follower is not necessarily a moderator or contributor?  I don't see any option in the UI to follow a channel (just posts), but the `Channel` object returned by the API includes the following attributes:
```
 user_is_contributor
 user_is_moderator
 user_is_subscriber
```
I'm assuming that a user is a follower if `user_is_subscriber` is true?  And we should store all the above in Django: a channel's moderators, contributors, and subscribers?

**Comment by Ferdi** [comment]
> is it correct that a channel follower is not necessarily a moderator or contributor?
Yes. 
Private channels have:  contributors, moderators, and subscribers
Public channels have :  Moderators and subscribers

"Subscribe" just affects your front page feed .  So for example, you can be a member of a private channel but you unsubscribe because the channel is noisy and you dont want that channel to dominate your feed.  But you are still a member and can access the channel if you wanted.

**Comment by mbertrand** [comment]
@pdpinch I checked the last checkbox, ok to close?
