### ISSUE TITLE
Search Profiles

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1461]
As a user, I'd like to be able to search user profiles. There are a few use cases:

- [ ] **Private channels**: As a member or moderator, I can search the profiles of members (contributors) and moderators. 
- [ ] **Restricted channels**: As a user, I can search the profiles of members (contributors), moderators and followers (subscribers)
- [ ] **Public channels**: As a user, I can search the profiles of all followers (subscribers) and moderators. 
- [ ] **Site search**: As a user, I can search the profiles of all users 

### acceptance criteria:
- [x] #1451  Profiles should update channel membership when they are subscribed or unsubscribed
- [x] #1453 author_channel_membership should be indexed as an array instead of a comma delimited string
- [x] #1420 keep track of channel followers
- [x] profile search front end:
  - [x] add profile search to channel query
  - [x] add profile search to site query
  - [x] display profile card in search results
 
### related issues
-  allow sorting of posts and comments, but not profiles

**Comment by mbertrand** [comment]
@pdpinch I think these should all be possible as long as `author_channel_membership` values are correct in the profile index, it's just a matter of sending the correct search parameters from the front end.

**Comment by mbertrand** [comment]
The query for profiles in a specific channel should include a filter for `{"query":{"terms":{"author_channel_membership": ["<channel_name>"]}}}`.  Assuming that a private channel has no subscribers who are not also moderators or contributors, then the first 2 checkboxes should just work with no more than that filter.  

For public channels, do you want to exclude moderators and contributors from search, and return only subscribers?  If not, then the above filter should still work, otherwise will will need to add an `author_channel_subscriptions` field and filter against that.

To search site-wide for all profiles, do not include any channel filter.

**Comment by pdpinch** [comment]
@mbertrand I confirmed with Ferdi. The profile search in public channels should return followers (subscribers) and moderators. (It can also return contributors, but there shouldn't really be any of those for public channels). 

I've update the description to reflect this.

**Comment by pdpinch** [comment]
updated the description to include the front-end

**Comment by pdpinch** [comment]
@mbertrand @noisecapella do you think we can close this?

**Comment by mbertrand** [comment]
Yes
