### ISSUE TITLE
Widgets

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#1491]
As a channel moderator, I need to be able to add a widget to my channel. As a user, I need to be able to view the widget. 

for @mitodl/zagaran-inc:
- [x] mitodl/open-widget-framework#10 Refactor to DRF-based views
- [x] mitodl/open-widget-framework#3 JavaScript tests
- [x] mitodl/open-widget-framework#11 widget wrapper example
- [x] mitodl/open-widget-framework#15 update documentation 
- [x] mitodl/open-widget-framework#13 use yarn for JS packages

for @mitodl/odl-engineering:
- [x] #1441 add widgets framework
- [x] #1458 Widgets: Feature flag
- [x] #1460 include channel widgets on channel page, post detail page
- [x] #1459 Authentication and Authorization

**Comment by pdpinch** [comment]
@jklingen92 @kyfantaz @rhysyngsun @Ferdi I pulled together this Epic with a list of the current, open issues. (There's a checklist now in the description) 

Can you let me know what's missing?

**Comment by jklingen92** [comment]
@pdpinch issues #10 and #11 are in pull requests on the widget-framework and widget-sample-app repos respectively. As soon as they're reviewed they'll be ready to merge in.

**Comment by pdpinch** [comment]
Editing and managing widgets isn't complete yet, but we have a separate issue for that, #1508
