### ISSUE TITLE
Article: Cover Image

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1492]
#### Requirements

- Allow the author of the article to set a cover image on an article post type
- A thumbnail of this cover image should show up on the frontpage and the channel feed
- The cover image should be displayed inline on the post detail page similar to how url posts display the embedly preview

###### #1593 Backend
- [x] Add a `cover_image` file field to the `Article` 
- [x] Support setting the cover image via the API when the post is created
- [x] Return the cover image in post APIs (listing and single-post)

###### Frontend editor
- [x] #1594 Implement an UI similar to LinkedIn's editor
- [x] #1595 Display a thumbnail of the cover image on the frontpage
- [x] #1595 Display a thumbnail of the cover image on the channel post list page
- [x] #1594 Display the cover image similarly to embedly image previews on the post detail page

###### Search
- [x] #1596 Add the article thumbnail to the search index 

#### Questions

- For the frontend should we reuse our existing `thumbnail` field, or would a `article_thumbnail` be better?
- Should the author be able to edit the cover image after the post has been created?
- What dimensions should this image have?
- Is cover image optional or required?
- Should we generate a thumbnail-sized copy of this for the frontpage / channel pages?
  - If the dimensions for display on the post detail page are different than the dimensions displayed on post list pages, how should that thumbnail be cropped (e.g. if the cover image is a wide image, we may want "crop to fit vertically and center in image")

**Comment by pdpinch** [comment]
Some answers to the questions in the description: 

> • For the frontend should we reuse our existing thumbnail field, or would a article_thumbnail be better?

I don't see any reason to add another type of thumbnail. The use and the behavior should be the same. 

> • Should the author be able to edit the cover image after the post has been created?

Yes, unless there's a serious blocker for editing. 

> • What dimensions should this image have?

TBD

> • Is cover image optional or required?

Optional. 

> • Should we generate a thumbnail-sized copy of this for the frontpage / channel pages?

Yes. If we can, we should use the same design and tooling that we do for link posts with a thumbnail. 

The article thumbnail should be cropped the same way we do it for link posts with thumbnails. I know we use an embedly service for image resizing, so we may need alternate tooling.

**Comment by pdpinch** [comment]
Answers & opinions about some of the questions: 

> - Should the author be able to edit the cover image after the post has been created?

  **A:** Yes

> - What dimensions should this image have?

  optimize for the post summary page 

> - Is cover image optional or required?

  **A:** Optional

> - Should we generate a thumbnail-sized copy of this for the frontpage / channel pages?

  **A:** Probably, but if it's easier, we can continue for now to use the same image service we use for embedly. 

>  - If the dimensions for display on the post detail page are different than the dimensions displayed on post list pages, how should that thumbnail be cropped (e.g. if the cover image is a wide image, we may want "crop to fit vertically and center in image")

  **A:** cropping should be the same as existing thumbnail cropping, i.e. the crop is centered horizontally and the width adjusts with the viewport width.

**Comment by pdpinch** [comment]
Oops. I should read the comments (that I wrote!) before commenting.
