### ISSUE TITLE
Article: support as a configurable post type in channels

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1495]
We want to allow moderators to configure the channel as allowing or disallowing article post types.

- Existing channels settings should not change
- New channels should default to only `link | text`

### Design

- In order to permit article post types, these are shadowed in reddit as a text (self post) with no content
- This means if a channel wants to be configured to only allow article post types, we need to permit text posts in reddit, but disallow them at the api layer.
- To accomplish this, we need to define a new source of truth in the database for `allowed_post_types`.
- Since we're moving validation of the link types to our API layer, we should update channel settings to permit "any" link type so we don't have to bother with the complexity required to translate our expanded post type settings into equivalent reddit settings.

###### Stage 1
- [ ] shadow `allowed_post_types` in `Channel`, update the API to set this value on subsequent channel API requests (creates + updates) and return it as a new field in `GET`s
- [ ] update to frontend to check both `link_type` and `allowed_link_types`, with the latter having precendence
- [ ] backpopulate `Channel.allowed_post_types` and `Post.post_type` given the above logic
###### Stage 2
- [ ] update the posts API to validate new posts against `Channel.allowed_post_types`
- [ ] default new channels to "any" link type
- [ ] update all channels' reddit settings to permit "any" link type
###### Stage 3 - _(permitting enough time from stage 1 deployment for clients to update)_
- [ ] update the UI to display articles as a post type option
- [ ] remove all logic around `link_type`

**Comment by pdpinch** [comment]
@rhysyngsun I think this is all done?

**Comment by rhysyngsun** [comment]
Yup
