### ISSUE TITLE
Production Deployment

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#165]
## "Production readiness" checklist (based off of [MIT ODL handbook](https://github.com/mitodl/handbook/blob/master/production-ready.md))

- [x] Finalize DNS names
    - [x] Configure Route 53 
        - [x] ci 
        - [x] rc 
        - [x] prod
- [x] Configure Heroku App domain
- [ ] Configure the following services:
    - [x] Mailgun domain
    - [ ] Google analytics
    - [x] Sentry
    - [x] New Relic
    - [x] Email address (Moira; if necessary) 
- [x] Add branches to repo
    - [x] release-candidate
    - [x] release
- [x] Verify Heroku settings for (ci, rc, prod) environments:
    - [x] dyno types and adds-on
    - [x] Verify deploy settings are configured
    - [x] Add Heroku Config Vars based on app.json
    - [x] Verify that access is granted to team members
- [x] Configure Heroku Pipeline
- [x] Verify that Heroku app is communicating with reddit EC2 instance securely
- [x] Request InCommon web cert from IS&T for prod app
- [x] Configure HireFire for dyno autoscaling for prod app
- [ ] Ship Reddit logs to Elasticsearch
- [ ] Synchronize MM users to discussions
- [x] Run load tests
- [ ] Merge and deploy https://github.com/mitodl/micromasters/pull/3661

### Required features:
- [x] Does it support configuration via environment variables?
- [x] Does it support configuration via flatfile (e.g. YAML)?
- [x] Does it have a sane default configuration (e.g. as close to a realistic production configuration as possible)?
- [x] Does it run on parallel HTTP workers? (e.g. uWSGI, Gunicorn)?
- [x] Does it log to standard out/error?
- [x] Does it log to syslog?
- [x] Can it send stack trace emails to a configurable email list?
- [x] Does it have configurable log levels (e.g. DEBUG, ERROR, WARNING, INFO)?
- [x] Does it have a test suite which measures code coverage?
- [x] Does it have a status route (which requires a secret token) that can be used for health checking by a monitoring service?
- [x] Does the health check validate that each service the app depends on is reachable (e.g. databases, caching, external APIs when necessary)?
- [x] Does the health check return a response body with the availability information above in a machine-readable format in all cases?
- [x] Does the health check return a 500 status code when any component in the health check is detected to be failing?

### Required documentation/service infrastructure:
- [x] Does it have continuous integration builds which run the full test suite?
- [x] Does it have an automated continuous delivery to a development environment?
- [x] Does it have a documented release process?
- [x] Does its release process include staging and production builds, where staging builds are promoted to production?
- [x] Does its release process require that code changes be "signed off" as working on staging before being promoted to production?
- [x] Does it have application/resource monitoring in production (e.g. New Relic agent)?
- [x] Does it have service availability monitoring in production (e.g. periodic health checks with New Relic)?
- [x] Does it have automated, periodically generated, fully restorable backups for each non-ephemeral data store in production?

**Comment by pdpinch** [comment]
I think we can close this now.
