### ISSUE TITLE
Course search

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#1720]
- [x] Create and populate a search index with mappings for courses #1717

- [x] Add triggers/methods to update the ES index when existing courses are updated #1718

- [ ] Add the ability to search for courses in the front-end #1719

**Comment by pdpinch** [comment]
I think we can close this.
