### ISSUE TITLE
Improve Email Sending Resilience

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#1985]
We've stepped up the scale of email we send so we probably want to improve the performance at which we send emails. Capturing some issues we noticed:

- [ ] There's some kind of slow memory leak in sending frontpage emails (#1983)
- [x] The `notifications.tasks.send_weekly_frontpage_digests` task takes a while to complete. We probably need a fan-out structure here
- [ ] Correctly size and possibly dedicate a worker to email sending. Currently pending emails and various other tasks pile up behind the queuing.

**Comment by pdpinch** [comment]
@rhysyngsun do you think we can close this. I think you addressed the 2nd and 3rd point and the first point has its own issue.

**Comment by rhysyngsun** [comment]
@pdpinch it could still use some work to avoid bottlenecking effects
