### ISSUE TITLE
LearningResource: Bootcamps migration

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2044]
We need to phase this in over several PRs to keep the review size down and deliver this safely without breaking existing user experience. Each checkbox here should correspond to a PR and those PRs should be release separately

- [x] #2041 - Update bootcamp data ingestion to double write to `Course` and `Bootcamp` tables (PR #2036)
- [x] #2042 Update indexing code in the `search` app to index `Bootcamp` table
  - Update `search.tasks.start_recreate_index` to index bootcamps separately from `Course`, because those indexed documents are uniqued on `Course.course_id` and we're losing the integrity guarantee that having all data in `Course` gave us
    - You'll need to add corresponding `index_bootcamps`, indexing serializer methods and class as well, it'll probably more or less be a copy of the current search indexing, but it needs to get indexed under a new `bootcamp` type.
    - in `search.api._apply_general_query_filters`, line 124, add the new bootcamp type
- [x] #2043 Update frontend code to additionally search for `bootcamp` record types
  - This is when we should add a migration to drop the bootcamp records from `Course`
  - Remove code populating bootcamp records into `Course`

**Comment by pdpinch** [comment]
Looks like this epic has been completed for some time.
