### ISSUE TITLE
Epic: Course Search

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2090]
This is an epic to group everything we need to get Course Search functional in one place

- Backend
  - [x] [Remove course_catalog code writing bootcamp data to the Course model](https://github.com/mitodl/open-discussions/issues/2086)
- Favorites UI
   - [x] [UI for adding/removing an item to favorites](https://github.com/mitodl/open-discussions/issues/2091)
   - [x] [Display list of favorites](https://github.com/mitodl/open-discussions/issues/2092)
- [Search UI Redesign](https://github.com/mitodl/open-discussions/issues/1997)
  - [x] New design for cards
  - [x] [Update facets on search page](https://github.com/mitodl/open-discussions/issues/2043)
  - [x] [Change search from list to grid](https://github.com/mitodl/open-discussions/issues/2089)

**Comment by pdpinch** [comment]
All the issues in this epic have been done for some time.
