### ISSUE TITLE
Epic: Course run support in search

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2113]
#### Summary
Currently we are pulling course runs from mitx into individual `Course` records - this means that in the search they appear as separate results even though they're under a single logical course. We want to adjust our functionality around these to reflect this. This will support both the MITX integration as well as Micromasters (since it's a subset of MITX data) and xPro.

- [x] #2114 Data model for course runs
- [x] #2115 mitx course catalog import should write to course runs
- [x] #2116 Index courses and course runs
- [x] #2122 Add course run data to course api
- [x] #2123 Update Availability facet to work with revised search index structures
- [x] #2124 Update course drawer to open for the appropriate course run
- [x] #2125 OCW courses that are deleted should viewable directly, but not searchable
- [x] #2126 Add CourseRun to django-admin

#### Related Issues

- [x] mitodl/micromasters#4353 - Create endpoint to query for program metadata
- [x] mitodl/mitxpro#926 - Create endpoint to query for course and program metadata
