### ISSUE TITLE
Epic: Video Search

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#2302]
#### Data models
- [x] #2306 Implement a new `VideoResource` data model
  - Should be a subclass of our abstract LearningResource model
  - Add relevant fields to this new subclass, where fields are common, they should align to our existing search mappings if possible 
  - Transcripts will probably be the only field we don’t already have an equivalent for this
#### Data ingestion pipeline (ETL):
- [x] #2303 Fetching data (aka `extract` functions):
  - Function to fetch a list of a channel’s videos w/ required metadata
- [x] #2304 Normalizing data (aka `transform` functions):
  - Normalizes data returned from the extract function into a normalized structure matching our DB schema
- [x] #2305 Saving data (aka `loader` functions):
  - Writes normalized data into the database (including any nested writes)
  - Triggers celery tasks to index the new DB record into ElasticSearch
- [x] #2307 Search Indexing
  - Add a new ES serializer for `VideoResource`
  - Indexing API methods
  - Indexing and reindexing tasks
#### Data ingestion triggers
- [x] #2317 Historical data
  - Implement as a once-time backpopulate management command that executes our ingestion pipeline for each channel
  - We probably want a flag that lets us specify an individual channel for this command as well so we don’t have to sync everything just to add a channel
- [x] #2335 Cron jobs to pull in periodic data
  - Use APIs integrated with in #2303 
  - Configurable frequency of checks
- [x] #2375 Transcript data
  - Use pytube to pull caption data
  - Parse caption data to generate transcript
- [x] #2376 Cron jobs for transcript data
  - Cron job to download transcripts for new videos
  - Cron job to periodically update transcript for old videos
#### Search UI
 - [x] #2332 support favoriting videos

**Comment by rhysyngsun** [comment]
Closing this because aside from a few loose ends we're done with the bulk of the implementation

**Comment by pdpinch** [comment]
🎉
