### ISSUE TITLE
User Lists and Learning Paths

### ISSUE THREAD

**Issue by mbertrand** [mitodl/open-discussions#2314]
UI for learning paths and user lists
- [x] Modify UserList API to support creation/deletion/updates #2321
- [x] Create a basic page to view lists/pathways #2310 
- [x] Create a page to view contents of lists / pathways #2364
- [x] add ability to edit lists / pathways #2311
- [x] and their metadata #2370
- [x] List/pathway creation form #2312 
- [x] UI for adding learning resources to a list #2313 
- [x] Show learning path details in the drawer #2266
- [x] show the favorites as a list on the userlist index page #2351
- [x] add ability to delete userlists to the user list index page #2353
- [x]  implement "Add New List" button on "Add To List" Dialog #2357

**Comment by rhysyngsun** [comment]
Closing this as all the child issues are done
