### ISSUE TITLE
Production deployment checklist

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#268]
- [ ] Prior to syncing users, `FEATURE_OPEN_DISCUSSIONS_USER_SYNC=True` needs to be set. Reddit, OD, and MM should otherwise be correctly configured before this as profile updates will immediately trigger errors if not.
- [ ] run management command for populating users:
  On MicroMasters, run: `./manage.py backfill_discussion_users`
- [ ] To display the "Create Channel" button in MM, set `FEATURE_OPEN_DISCUSSIONS_CREATE_CHANNEL_UI=True` in MM

**Comment by rhysyngsun** [comment]
I don't think we need this anymore.

**Comment by pdpinch** [comment]
Nope. Thanks.
