### ISSUE TITLE
Expose channel GA tracking ID to channel owners

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3305]
As a channel owner, I'd like to be able to set the Google Analytics tracking ID for my channel, so I can gather standard analytics about it. 

There is already a field on the channel model for this and, I presume it includes the GA tracking code on the channel and posts. However, the only way to set the value is through the django admin. This issue is to expose the setting to channel owners, through the channel admin. 

#### Designs and Mockups

none, as yet.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/430126/109538553-3a7ac080-7a8e-11eb-88f1-524e9636e5d8.png">
 

#### Acceptance Criteria:

- [ ] Add an "Analytics" card to the "Basic" tab of the channel admin
- [ ] Add a simple text field form to the card, when updated save to the `ga_tracking_id` field on the channel object
- [ ] minimal validation on the code that's added 
- [ ] While we're at it, please update the "Other" card title to "Notifications"
