### ISSUE TITLE
Dashboard for MicroMasters channels

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#3342]
As a MicroMasters team member, I'd like to know how the MicroMasters channel is growing over time, in particular the mmmcredentialholders channel. 

#### Acceptance Criteria:

- [ ] Cumulative number of users in mmcredentialholders channels (draft at https://bi.odl.mit.edu/queries/1046#1839) 
- [ ] Cumulative number of users in all micromasters channels (draft at https://bi.odl.mit.edu/queries/1041#1828) 
- [ ] Posts to all micromasters channels over time (draft at https://bi.odl.mit.edu/queries/1042#1831)
- [ ] Comments to all micromasters channels over time (broken draft at https://bi.odl.mit.edu/queries/1042#1832) 
- [ ] organized into a dashboard similar to https://bi.odl.mit.edu/dashboard/discussions-analytics

#### Questions

- What are all the micromasters channels?

#### Out of Scope

- anything that is better handled by Google Analytics, like pageviews.

**Comment by pdpinch** [comment]
Here's the list of MicroMasters channels:

mmcredentialholders 
mmsdsholders
DEDPhelp
DEDPmasters2021 
mmfingeneral
pom
mmsdsbreca
mmsdsjobs
mmsdsgeneral
mmdedpholders
supplychainmanagement
pom3pluslearners
CFx_Prep
DEDP_Jobs
scm_jobs
mm_scm_holders
DEDP

**Comment by abeglova** [comment]
The dashboard is RFR
Dashboard:
https://bi.odl.mit.edu/dashboard/channel-metrics?p_channels=%20%27mmcredentialholders%27

Registered users query:
https://bi.odl.mit.edu/queries/1052?p_channels=%27mmcredentialholders%27

Posts query:
https://bi.odl.mit.edu/queries/1053?p_channels=%20%27mmcredentialholders%27

Comments query:
https://bi.odl.mit.edu/queries/1055?p_channels=%20%27mmcredentialholders%27

**Comment by pdpinch** [comment]
I've shared this with the MM team. If they have follow-up requests, I'll put them in a new issue.
