### ISSUE TITLE
Epic: Remove all dependencies on Reddit

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#3568]
The functionality we need to address is:

#### Posts

- [ ] Add a table tracking who has voted on witch posts
- [ ] When a posts voted on, store/update/delete that data from the voting table
- [ ] Update the APIs that return data as to whether the current user has voted on a post to use the DB

#### Comments

- [ ] Add a table tracking who has voted on witch comments
- [ ] When a comments voted on, store/update/delete that data from the voting table
- [ ] Update the APIs that return data as to whether the current user has voted on a comment to use the DB

#### Channels

- [ ] Channel listing should query the database and support existing algorithms

#### Moderation
- [ ] Update the moderator management APIs to query the database instead of Reddit
- [ ] Add a table to track reported posts and comments
- [ ] Update the APIs for reporting comments and posts to write to the database
- [ ] Update the moderator APIs to manage reported content to use the database

# Frontpage

- [ ] Frontpage listings should query the database and support existing algorithms

#### Cleanup

- [ ] Remove all references to Reddit APIs and remove `praw`
