### ISSUE TITLE
Store site-specific data (e.g. redirect urls, site name, etc)

### ISSUE THREAD

**Issue by rhysyngsun** [mitodl/open-discussions#444]
Currently we have a certain amount of data either a) hardcoded in this app or b) stored in the shared cookie. This data doesn't differ user-to-user so we should instead store a key in the cookie and move this data into the DB under a `Site`/`Application` record that can be managed in django-admin. We also can't add anything else to the cookie because it's already too big, so this will in general clean things up. It also lines us up nicely to support multiple sites/applications down the road.

Values we need to port (examples not actual values):

- [x] Site name (e.g. "MicroMasters", currently hardcoded)
- [x] Site homepage (e.g. "micromasters.mit.edu", currently in settings.py)
- [x] Site auth/external login url (e.g. "micromasters.mit.edu/discussions", currently in the cookie and settings.py)
- [x] Site token session url (e.g. "micromasters.mit.edu/discussions_token", currently in the cookie)
- [x] TOS link (currently hardcoded)

#### Deployment

This work should probably be done in a few phases to avoid breaking things:

- [x] Add this model and django-admin UI (PR #444)
- [x] Migrate all environments
- [x] In the following envs create a record for MM and set `OPEN_DISCUSSIONS_DEFAULT_SITE_KEY`:
  - [x] CI
  - [x] RC
  - [x] Prod
- [x] Deploy update to open-discussions to take the value from the DB based on cookie key or default to MM (i.e. no longer use the token) (PR #492)
- [ ] Deploy update to MM to set only the key in new sessions (PR mitodl/micromasters#3834)

After this work is complete, we can remove all the extraneous hardcoded data and data stored in the cookie.

**Comment by pdpinch** [comment]
The size of this cookie has continued to cause problems for me, especially on *.odl.mit.edu domains.
