### ISSUE TITLE
Mail: periodic front-page digest emails

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#450]
As a learner, I'd like to (optionally) get email updates of recent changes to the Discussion's front page. 

### acceptance criteria
- [x] Learner receives regular e-mails with a list of top posts from their feed
  - [x] By default all members in OD get the daily e-mail, except for those who have already opted out of MM mail 
  - [x] #460 weekly subscribers (top)
  - [x] #461 daily subscribers (hot)
- [x] we should not send e-mail to a particular learner if there is not enough new posts since last mailing
- [x] #462 e-mail template should be responsive
- [x] E-mail template has a link to the settings for the user to unsubscribe or change the frequency 
  - [x] #451 UI
  - [x] #459 Model and API 
- [x] #534 Ensure email addresses have been backpopulated
- [x] #536 Add mail tasks to cron once everything is ready
- [x] #541 Ensure new users get NotificationSettings
- [x] #535 Ensure `NotificationSettings` have been backpopulated

**Comment by pdpinch** [comment]
Blocked by #451 -- we don't want to start sending these emails without a way to opt out.

**Comment by roberthouse54** [comment]
![image](https://user-images.githubusercontent.com/20047260/35813886-c0c0ad02-0a62-11e8-9201-e5797ddfee63.png)

**Comment by rhysyngsun** [comment]
Everything is done for this
