### ISSUE TITLE
Allow user to follow posts (but not comments)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#464]
As a user, I'd like to be able to "follow" a post so that I will be notified (by email) whenever there is a new comment on it. 

### acceptance criteria
- [x] model for tracking post/comment subscriptions #465 
- [x] Mail: API for follow / unfollow #468 
- [x] modify comment method to send updates when there are subscribers #467 
- [x] email template for new comment notifications #470 
- [x] button for follow / unfollow (or subscribe / unsubscribe) #469 
- [x] automatically subscribe users to their own posts and comments #466 
- [x] model and API updates for setting automatic subscriptions on/off #475

**Comment by rhysyngsun** [comment]
Closing this out as we're feature complete in prod.
