### ISSUE TITLE
Digest Mail template tweeks

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#572]
- [x] #577 we need a better return address than "no-reply@discussions.odl.mit.edu"
- [x] #578 Subject line could be improved too: "Open Discussions - Recent Popular Posts"
- [x] #574 The mobile view needs less padding, in order to decrease the text-wrapping
- [x] #578 Can we tighten up the header? In mobile (mid-size screen), the logo and intro text take up half the view and only one post is visible
- [x] #576 anonymous profile image is missing for user's without a profile image

**Comment by pdpinch** [comment]
Some of these are going to be easier to fix than others.

**Comment by roberthouse54** [comment]
Padding is being addressed in PR #574
