### ISSUE TITLE
Public channels (anonymous read-only access)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#598]
As a user, I'd like to view some channels' content without logging in. 

As a search engine crawler, I need to crawl and index public channels' content. 

### acceptance criteria
- [ ] allow anonymous access to frontpage API
- [ ] allow anonymous access to channels API
- [ ] allow anonymous access to posts API
- [ ] allow anonymous access to comments API
- [ ] don't force redirect to /auth_required on index.html
- ? UI changes?

**Comment by pdpinch** [comment]
This is done for now.
