### ISSUE TITLE
User signs up / logs in with e-mail

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#770]
### acceptance criteria
- [x] #700 UX for login page
- [x] #701 UX for sign up page
- [x] #678 add log in / sign up buttons to top nav
- [x] #675 3rd party login error handling
- [x] #672 recommend users with MIT email login with Touchstone

### out of scope
- "home page" for not-logged-in user: currently we have no content for users who haven't signed up with MicroMasters. 
- linking to privacy policy

**Comment by rhysyngsun** [comment]
All of the sub-tasks for this have PRs up or are closed, so I'm going to close this story before it gets buried again.
