### ISSUE TITLE
User continues to be able to log in with MicroMasters

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#774]
As a MicroMasters users, I still want to be able to view my front page feed on the MicroMasters dashboard, and be able to log in with my MicroMasters account. 

At the same time, the flow for creating a new user MM account is less than ideal. So we would like to restrict MM login to only existing accounts. 

### acceptance criteria:
- [x] https://github.com/mitodl/open-discussions/issues/840 back populate MM social auth objects for existing MM users
- [x] https://github.com/mitodl/open-discussions/issues/843 only display the "login with MIcroMasters" button to users who only have MM as the authentication method
- [x] https://github.com/mitodl/open-discussions/issues/841 create user API should merge accounts if they match an existing one on email
- [x] https://github.com/mitodl/micromasters/issues/3988 Update MM configuration to use auth end-point for logging into discussions

### related issues (out of scope)
- user can log out
- Rename default `AuthenticatedSite` to "Discussions"
- remove legacy JWT code, replace with code that directs to /login
