### ISSUE TITLE
SEO: basic meta tags on post detail pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/open-discussions#866]
As a search crawler, I expect metadata to be standardized for easy parsing

### acceptance criteria
- [x] page title = title of post
- [x] description metadata field is set to first 300 characters of post, truncated at a word boundary 
- [ ] keywords metadata field is set to words in channel.title (for now) 

### out of scope
- google snippets 
- schema.org 
- social sharing metadata (twitter, facebook, etc.)

**Comment by mbertrand** [comment]
@pdpinch for keywords: use every word in the title? Strip out articles/conjunctions ('a', 'an', 'the', 'but', 'or', 'if', etc)?  What about foreign languages?

**Comment by mbertrand** [comment]
@pdpinch no keywords anymore, right?
